{{- if .Values.deployOperator }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.name }}-operator-group
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    {{- include "threescale.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    olm.providedAPIs: 'APIManager.v1alpha1.apps.3scale.net,APIManagerBackup.v1alpha1.apps.3scale.net,APIManagerRestore.v1alpha1.apps.3scale.net,ActiveDoc.v1beta1.capabilities.3scale.net,Application.v1beta1.capabilities.3scale.net,ApplicationAuth.v1beta1.capabilities.3scale.net,Backend.v1beta1.capabilities.3scale.net,CustomPolicyDefinition.v1beta1.capabilities.3scale.net,DeveloperAccount.v1beta1.capabilities.3scale.net,DeveloperUser.v1beta1.capabilities.3scale.net,OpenAPI.v1beta1.capabilities.3scale.net,Product.v1beta1.capabilities.3scale.net,ProxyConfigPromote.v1beta1.capabilities.3scale.net,Tenant.v1alpha1.capabilities.3scale.net'
spec:
  targetNamespaces:
    - {{ .Values.namespace | default .Values.name | quote }}
  upgradeStrategy: Default
{{- end}}