apiVersion: v1
kind: ServiceAccount
metadata:
  name: system-redis
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    app: system-redis
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: system-redis
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    app: system-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: system-redis
  template:
    metadata:
      labels:
        deployment: system-redis
    spec:
      restartPolicy: Always
      serviceAccountName: system-redis
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 32Gi
            requests:
              cpu: '1'
              memory: 1Gi
          readinessProbe:
            exec:
              command:
                - container-entrypoint
                - bash
                - '-c'
                - redis-cli set liveness-probe "`date`" | grep OK
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: system-redis
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: REDIS_CONF
              value: /etc/redis.d/redis.conf
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: system-redis-storage
              mountPath: /var/lib/redis/data
            - name: redis-config
              mountPath: /etc/redis.d/
          terminationMessagePolicy: File
          image: 'registry.redhat.io/rhel9/redis-7'
      serviceAccount: system-redis
      volumes:
        - name: system-redis-storage
          persistentVolumeClaim:
            claimName: system-redis-storage
        - name: redis-config
          configMap:
            name: redis-config
            items:
              - key: redis.conf
                path: redis.conf
            defaultMode: 420
      dnsPolicy: ClusterFirst
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-redis-storage
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    app: system-redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: system-redis-service
  namespace: {{ .Values.namespace | default .Values.name | quote }}
  labels:
    app: system-redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    deployment: system-redis
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: {{ .Values.namespace | default .Values.name | quote }}
data:
  redis.conf: |
    protected-mode no

    port 6379

    timeout 0
    tcp-keepalive 300

    daemonize no
    supervised no

    loglevel notice

    databases 16

    #save 900 1
    #save 300 10
    #save 60 10000
    save ""

    stop-writes-on-bgsave-error yes

    rdbcompression yes
    rdbchecksum yes

    dbfilename dump.rdb

    slave-serve-stale-data yes
    slave-read-only yes

    repl-diskless-sync no
    repl-disable-tcp-nodelay no

    appendonly no
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes

    lua-time-limit 5000

    activerehashing no

    aof-rewrite-incremental-fsync yes
    dir /var/lib/redis/data

    rename-command REPLICAOF ""
    rename-command SLAVEOF ""